apiVersion: apps/v1
kind: Deployment
metadata:
  name: zas-web
  namespace: ${NAMESPACE}zasanddas
  labels:
    app: zas-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zas-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: zas-web
    spec:
      containers:
      - name: zas-web
        image: nhowell02/zasanddas:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        env:
        - name: DB_CONN
          value: Server=zas-db-svc;Username=postgres;Password=password;Database=postgres
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: SHOW_SWAGGER
          value: "true"
        - name: COLLECTOR_URL
          value: http://zas-otel-ser:4317
        readinessProbe:
          httpGet:
            path: /api/Inventory
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/Inventory
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10