apiVersion: v1
kind: ConfigMap
metadata:
  name: zas-prom-config
  namespace: ${NAMESPACE}zasanddas
data:
  config: |
    modules:
        tcp_connect:
            prober: tcp
            timeout: 5s  