apiVersion: v1
kind: ConfigMap
metadata:
  name: zasanddas-grafana-config
  namespace: zasanddas
data:
  config: |
    apiVersion: 1

    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://zasanddas-loki-svc:3100
        jsonData:
          timeout: 60
          maxLines: 1000
---
