apiVersion: v1
kind: ConfigMap
metadata:
  name: zasanddas-grafana-config
  namespace: ${NAMESPACE}zasanddas
data:
  config: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://zasanddas-loki-svc:3100
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://zas-prom-svc:9090
      - name: Zipkin
        type: zipkin
        url: http://zas-zipkin-svc:9411
        access: proxy
---
