apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chris-grafana-ingress
  namespace: chris-proj06
spec:
  rules:
  - host: "grafana.christyoung.duckdns.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chris-grafana-svc
            port:
              number: 6000
---
