apiVersion: v1
kind: Service
metadata:
  name: zas-grafana-svc
  namespace: ${NAMESPACE}zasanddas
spec:
  selector:
    app: zasanddas-grafana
  ports:
    - protocol: TCP
      name: grafana
      port: 6000
      targetPort: 3000
