apiVersion: v1
kind: ConfigMap
metadata:
  name: zas-graff-con
  namespace: zasanddas
data:
  grafana-datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
      - name: Zipkin
        type: zipkin
        url: http://zas-zipkin:9411
        access: proxy
