apiVersion: v1
kind: Service
metadata:
  name: zas-grafana-svc
  namespace: zasanddas
spec:
  selector:
    app: zas-grafana
  ports:
    - protocol: TCP
      name: grafana
      port: 6000
      targetPort: 3000
---
