apiVersion: v1
kind: ConfigMap
metadata:
  name: zas-otel-config
  namespace: zasanddas
data:
  config: | 
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            
    exporters:
      otlphttp:
        endpoint: http://zas-loki-svc:3100/otlp
      debug:
        verbosity: detailed
      prometheus:
        endpoint: 0.0.0.0:8889
      zipkin: 
        endpoint: http://zas-zipkin-svc:9411/api/v2/spans

    service:
      pipelines:
        traces: 
          receivers: [otlp]
          exporters: [zipkin]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          exporters: [otlphttp, debug]
---
