apiVerion: v1
kind: Service
metadata:
  name: zas-otel-svc
  namespace: zasanddas
spec:
  selector:
    app: zas-otel
  ports:
    - protocol: TCP
      name: grpc
      port: 4317
      targetPort: 4317
    - protocol: TCP
      name: http
      port: 4318
      targetPort: 4318
    - protocol: TCP
      name: other
      port: 55679
      targetPort: 55679
    - protocol: TCP
      name: prometheus
      port: 8889
      targetPort: 8889
---
