apiVersion: v1
kind: ConfigMap
metadata:
  name: zas-prom-config
  namespace: ${NAMESPACE}zasanddas
data:
  config: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["zas-otel-ser:8889"]
      - job_name: 'tcp_liveness'
        metrics_path: /probe
        params:
          module: [tcp_connect]
        static_configs:
          - targets:
              - zas-web-svc:8080
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: zas-blackbox-svc:9115
      - job_name: 'blackbox_exporter'
        static_configs:
        - targets: ['zas-blackbox-svc:9115']
---
