apiVersion: v1
kind: Service
metadata:
  name: zas-zipkin-svc
  namespace: zasanddas
spec:
  selector:
    app: zas-zipkin
  ports:
    - protocol: TCP
      name: zipkin
      port: 9090
      targetPort: 9090
---
