apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zas-zipkin-ingress
  namespace: ${NAMESPACE}zasanddas
spec:
  rules:
  - host: "zipkin.${SUBDOMAIN}zasanddas.duckdns.org"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zas-zipkin-svc
            port:
              number: 9411
---
