

@ZasAndDasAPI_HostAddress = http://zasanddas.duckdns.org
GET {{ZasAndDasAPI_HostAddress}}/api/inventory/getallstockitems
Accept: application/json
###
POST {{ZasAndDasAPI_HostAddress}}/api/inventory/addstockitem
Content-Type: application/json

{
  "name": "Wireless Mouse",
  "description": "A high-quality wireless mouse with ergonomic design.",
  "itemCategoryId": 1,
  "price": 29.99,
  "imagePath": "/images/products/wireless-mouse.jpg",
  "quantity": 150
}

###
