receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  otlphttp:
    endpoint: "http://loki:3100/otlp"
  debug: 
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
  zipkin: 
    endpoint: http://zas-zipkin:9411/api/v2/spans
  
service:
  pipelines:
    traces: 
      receivers: [otlp]
      exporters: [zipkin, debug]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      exporters: [otlphttp, debug]