name: automated testing
on:
- push
- workflow_dispatch

jobs:
    test:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: example
        run: |
          docker build \
          -f ./test.Dockerfile \
          -t chris_test_container \
          .
          docker run --rm chris_test_container
