name: automated testing
on:
- push
- workflow_dispatch

jobs:
    test:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: example
        run: |
          docker build \
          -f ./test.Dockerfile \
          -t chris_test_container \
          .
          docker run --rm chris_test_container

    pushtodocker: 
       runs-on: self-hosted
       needs: test
       steps: 

       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Create container and push
         run: |
            ls
            docker build \
            -t nhowell02/zasanddas:${{github.run_id}} \
            .


            docker push nhowell02/zasanddas:${{github.run_id}}

    pushtokubernetes:
        runs-on: self-hosted
        needs: [test, pushtodocker]
        steps:
        - name: deploy to kubernetes
          run: |
            export BUILD_NUMBER=${{github.run_number}}

            name: log to the console
on: 
- push
- workflow_dispatch
jobs: 
  automated_unit_testing:
    runs-on: self-hosted

    steps: 
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create container
      run: |
        cd Store
        ls
        docker build \
          -t nhowell02/simpleapi:${{github.run_id}} \
          .


        docker push nhowell02/simpleapi:${{github.run_id}}

    - name: Deploy to kubernetes
      run: |
        export BUILD_NUMBER=${{github.run_id}}
        ls
        for FILE in "k8s"/*
        do
          cat "$FILE" | envsubst 
          echo
          cat "$FILE" | envsubst | kubectl apply -f -

        done
        
