name: automated testing
on:
- push
- workflow_dispatch

jobs:
    test:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
  
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal


    