name: automated testing
on:
- push
- workflow_dispatch

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: example
        run: |
          docker build \
          -f ./test.Dockerfile \
          -t zas_test_container \
          .
          docker run --rm zas_test_container

    integrationtest:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: docker build tests
          run: |
            docker build \
            -f ./integrationtest.Dockerfile \
            -t zas_integration_test \
            .
            docker run -v /var/run/docker.sock:/var/run/docker.sock --rm zas_integration_test


    pushtodocker: 
       if: ${{ github.ref == 'refs/heads/main' }}
       runs-on: ubuntu-latest
       needs: [test, integrationtest]
       steps: 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Create container and push
         run: |
            ls
            docker build  -f ./Dockerfile \
            -t nhowell02/zasanddas:${{github.run_id}} \
            .


            docker push nhowell02/zasanddas:${{github.run_id}}

    pushtokubernetes:
        runs-on: self-hosted
        needs: [test, integrationtest, pushtodocker]
        steps:
        - name: deploy to kubernetes
          run: |
            export BUILD_NUMBER=${{github.run_id}}

            for FILE in "K8s"/*
            do
              cat "$FILE" | envsubst | kubectl apply -f -
            done

    notifydiscord:
        runs-on: self-hosted
        needs: [test, pushtodocker, pushtokubernetes]
        if: ${{ always() && contains(needs.*.result, 'failure') && (github.ref == 'refs/heads/main') }}
        steps: 
        - name: Discord notifications
          env:
            DISCORD_WEBHOOK:  ${{secrets.DISCORD_WEBHOOK}}
          uses: Ilshidur/action-discord@master
          with:
              args: '@everyone The project {{EVENT_PAYLOAD.repository.full_name}} pipeline has failed from commit {{GITHUB_SHA}} on run: https://github.com/ChristopherTYoung/ZasDasApp/actions/runs/${{github.run_id}}'
