name: automated testing
on:
- push
- workflow_dispatch

jobs:
    test:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: ${{ matrix.dotnet-version }}
      
      # - name: Install dependencies
      #   run: dotnet restore
      
      # - name: Build
      #   run: dotnet build --configuration Release --no-restore
        
      # - name: Test
      #   run: dotnet test --no-restore --verbosity normal


    
