name: automated testing
on:
- push
- workflow_dispatch

jobs:
    test:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4

      - name: get .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 9.0.x
            
      - name: example
        run: |
            sudo dotnet workload restore
            dotnet build

    
