name: automated testing
on:
- push
- workflow_dispatch

jobs:
    test:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: example
        run: |
            sudo apt-get update && \
            sudo apt-get install -y dotnet-sdk-9.0
            sudo dotnet workload restore
            dotnet build
