name: automated testing
on:
- push
- workflow_dispatch

jobs:
    test:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v4
      - name: example
        run: |
          docker build \
          -f ./test.Dockerfile \
          -t chris_test_container \
          .
          docker run --rm chris_test_container

    pushtodocker: 
       runs-on: self-hosted
       needs: test
       steps: 

       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Create container and push
         run: |
            ls
            docker build \
            -t nhowell02/zasanddas:${{github.run_id}} \
            .


            docker push nhowell02/zasanddas:${{github.run_id}}

    pushtokubernetes:
        runs-on: self-hosted
        needs: [test, pushtodocker]
        steps:
        - name: deploy to kubernetes
          run: |
            export BUILD_NUMBER=${{github.run_number}}

            for FILE in "Kubernetes"/*
            do
              cat "$FILE \n---\n" | envsubst | kubectl apply -f -
            done