name: backup database
on:
  - push

jobs:
    backup:
        runs-on: self-hosted
        steps:
        - name: backup
          env:
            POSTGRES_DB: ${{ secrets.POSTGRES_DB || 'postgres' }}
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD || 'password' }}
            POSTGRES_HOST: ${{ secrets.POSTGRES_HOST || '10.43.161.232' }}
          run: |
            backup_dir="./backups"
            if ! test -d "$backup_dir"; then
                mkdir $backup_dir
            fi
            kubectl port-forward svc/zas-db-svc 5432:5432 -n zasanddas &
            PGPASSWORD=$POSTGRES_PASSWORD pg_dump postgres > ./backups/backup-${{github.event.pull_request.number}}.sql \
                --host=$POSTGRES_HOST
                --username=$POSTGRES_USER
            backup_count=$(ls /backups | grep 'backup' | wc -l)
            max_files=4
            if [ "$backup_count" -gt "$max_files" ]; then
                oldest_file=$(find /backups -type f | sort | head -n 1)
                rm -f "$oldest_file"
            fi
            kill -9 $(lsof -ti :5432)
