# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - zasanddas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    integrationtest:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v4
        - name: docker build tests
          run: |
            docker build \
            -f ./integrationtest.Dockerfile \
            -t zas_integration_test \
            .
            docker run -v /var/run/docker.sock:/var/run/docker.sock --rm zas_integration_test
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read #This is required for actions/checkout
        needs: integrationtest
        steps:
        - uses: actions/checkout@v4
        - name: Set up .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.x'
        - name: change directory
          run: cd ./ZasAndDasWeb

        - name: Build with dotnet
          run: |
            cd ./ZasAndDasWeb
            dotnet build --configuration Release

        - name: dotnet publish
          run: |
            cd ./ZasAndDasWeb
            dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v4
          with:
            name: .net-app
            path: ${{env.DOTNET_ROOT}}/myapp

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT
            contents: read #This is required for actions/checkout
        steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: .net-app
      
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_187CFDC82C8E4F0381F2C11ADFA41755 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_97C3C59814564EB0866767F24D12F7D4 }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4C2D779527B0444DAC722C28B2C8976D }}

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: 'zasanddas'
            slot-name: 'Production'
            package: ./ZasAndDasWeb/publish
          