name: automated testing
on:
  pull_request:
    types: [opened]

jobs:
    createnamespace:
        runs-on: self-hosted
        steps:
        - name: kubectl
          run: |
            SUBDOMAIN = ${{github.ref}} | tr '[:upper:]' '[:lower:]'
            kubectl create namespace "${SUBDOMAIN}-zasanddas""

    notifydiscord:
        runs-on: self-hosted
        needs: [createnamespace]
        steps: 
        - name: Discord notifications
          env:
            DISCORD_WEBHOOK:  ${{secrets.DISCORD_WEBHOOK}}
          uses: Ilshidur/action-discord@master
          with:
              args: '@everyone Pull request environment created: ${{github.ref}}-zasanddas'
