name: automated testing
on:
  pull_request:
    types: [opened, closed]

jobs:
    createnamespace:
        if: github.event.action == 'opened'
        runs-on: self-hosted
        steps:
        - name: kubectl
          run: |
            kubectl create namespace ${{github.event.pull_request.number}}-zasanddas
                steps:
        - name: deploy to kubernetes
          run: |
            export BUILD_NUMBER=${{github.run_id}}
            export NAMESPACE=${{github.event.pull_request.number}}-
            export SUBDOMAIN=${{github.event.pull_request.number}}.
            for FILE in "K8s"/*
            do
              cat "$FILE" | envsubst | kubectl apply -f -
            done
    
    destroynamespace:
        if: github.event.action == 'closed'
        runs-on: self-hosted
        steps:
        - name: Delete namespace
          run: |
           kubectl delete namespace ${{github.event.pull_request.number}}-zasanddas

    notifydiscord:
        runs-on: self-hosted
        needs: [createnamespace, destroynamespace]
        if: always() && contains(needs.*.result, 'success')
        steps: 
        - name: Discord notifications
          env:
            DISCORD_WEBHOOK:  ${{secrets.DISCORD_WEBHOOK}}
          uses: Ilshidur/action-discord@master
          with:
              args: '@everyone Pull request environment ${{github.event.action}}: ${{github.ref}}-zasanddas'
